import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import styles from "./index.module.css";
import { Flex, Text } from "@mantine/core";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from ehcochamber!" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        direction={"column"}
        align={"center"}
        justify={"center"}
        sx={{ height: "100vh" }}
      >
        <Text>
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}{" "}
        </Text>
      </Flex>
    </>
  );
}
